mrash/fwknop

android/project/jni/fwknop/fwknop_client.c, android/project/res/layout/main.xml, android/project/src/com/max2idea/android/fwknop/Fwknop.java
This adds a "Server UDP Port" setting just below "Server Address". It allows the user to change the port the SPA packet is sent to.
=> android: allow definition of custom server udp port

doc/fwknopd.man.asciidoc, fwknop.spec, server/fwknopd.8.in, server/fwknopd_common.h
Having extra '/run' subdirectory hardcoded into paths used for options
'digest-file', 'pid-file', 'run-dir' is counterintuitive and can lead to
bogus directory layouts when 'localstatedir' differs from the default
value.
For example, if 'localstatedir' is set to '/run', which is a common and
recommended substitute for /var/run in many distros nowadays, then
fwknop files will be placed under /run/run/fwknop.
This changeset removes extra '/run' subdirectory from all relevant paths
by changing DEF_RUN_DIR. Default value of 'localstatedir' is changed to
'/var/run' so users who relied on the previous behaviour won't have to
bother changing anything.
This is tested and works. Gentoo have this patch applied since 2.6.0.
=> server: remove extra '/run' subdir from paths 

extras/apparmor/configure_args.sh, extras/apparmor/usr.sbin.fwknopd
Comments in the shipped AppArmor profile state that fwknopd is assumed
to be built with 'localstatedir=/var', which is misleading for several
reasons:
* AppArmor profile assumes that fwknopd's pidfile and digest cache are
under /run/fwknop by the looks of it, i.e. 'localstatedir' is '/run'.
* By default these files are placed under /var/run/fwknop. Thus this
profile implicitly relies on the existence of '/var/run -> /run' symlink
and won't work otherwise when 'localstatedir' is '/var'
Since GitHub PR #152 was merged, 'localstatedir' can be simply set to
'/run' for AppArmor users to avoid this confusion. This changeset does
it.
If anyone had it working before, they should have it working now as the
shipped AppArmor profile required /run existence before as well.
=> extras: adjust 'localstatedir' value for the AppArmor profile

server/pcap_capture.c
This commit fixes fwknopd becoming non-responsive should the interface
temporarily cycles through a down state.  Verified on CentOS 7.
=> [server] daemon exits if listened-to interface goes down

extras/systemd/fwknopd.service, extras/systemd/fwknopd.tmpfiles.conf
Hello.
fwknopd daemon is packaged at least for Fedora, Debian and Gentoo. All these distros allow their users to have systemd as the initialization system. Currently, fwknop does not provide any systemd-related configuration.
It would be nice to have a basic, yet working unit file (systemd equivalent for classic initscripts) and tmpfiles.d configuration (a way to tell systemd to fill /run directory with directories in case when /run is tmpfs).
This will ease maintaining for systemd-distros and those who don't use systemd can simply ignore these files since they are small and not getting in the way.
=> extras: add systemd unit file and tmpfiles.d configuration for fwknopd

server/fwknopd_common.h, server/incoming_spa.c
The idea here is to support X-Forwarded-For header for HTTP requests proxied from a frontend, for example, when we use '-s' IP-autodetection flag from the client. So when we have some complex multi-tier setup, it would be good to pass client's real IP address in some header.
There could be an option to customize the header name as well. Probably we should think of "trusted" sources too, like it's done for every modern HTTP-server's module (mod_rpaf for Apache, mod_realip for nginx, mod_extforward for LigHTTPD).
This is just the first draft of the solution; thoughts/patches are welcome.
=> X-Forwarded-For HTTP header support

lib/fko.h, lib/fko_hmac.c, lib/hmac.c, lib/hmac.h
Adds a missed CUnit declaration in the first commit.  Second commit implements hardening/null checks as discussed in previous pull.
=> Hmac hardening

configure.ac, lib/Makefile.am, lib/fko_user.c
@mrash @damienstuart This does seem to fix the issues I was having.  I thought I had this all fixed without some of these changes, but with further work, this does all seem to be needed.
=> Fixes to allow for MINGW32 compilation

server/access.c, server/access.conf
This contains logic that allows an access.conf stanza to be ignored if it contains an include_keys directive that doesn't contain valid keys.
=> Include keys

lib/Makefile.am
This gets the dll building properly on mingw on both my Linux and Windows 7 installs of that toolchain.
=> Add yet another Mingw fix, Fixes dll build

server/access.c
add_port_list_ent() only supports one protocol/port entry at a time. The second entry was ignored.
This fix allows the CUnit test to pass, and also increases the CUnit code coverage as a result.
=> Modify server/access.c CUnit test to use the correct function.

extras/apparmor/usr.sbin.fwknopd
Error: 
$ sudo fwknopd -f -c /etc/fwknop/fwknopd.conf 
Starting fwknopd
Added jump rule from chain: INPUT to chain: FWKNOP_INPUT
iptables 'comment' match is available
Sniffing interface: ppp0
[*] pcap_open_live() error: ppp0: You don't have permission to capture on that device (socket: Permission denied)
Syslog:
[...] kernel: [...] type=1400 audit([...]): apparmor="DENIED" operation="create" profile="/usr/sbin/fwknopd" pid=[...] comm="fwknopd" family="packet" sock_type="dgram" protocol=768
=> Fix Ubuntu AppArmor regression

client/Makefile.am
When trying to build on my up to date Cygwin installation, I got the following error:
```
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall -Wformat -Wformat-security -fstack-protector-all -fstack-protector -D_FORTIFY_SOURCE=2  -Wall -Wformat -Wformat-security -fstack-protector-all -fstack-protector -D_FORTIFY_SOURCE=2 -o fwknop.exe fwknop-fwknop.o fwknop-config_init.o fwknop-spa_comm.o fwknop-utils.o fwknop-http_resolve_host.o fwknop-getpasswd.o fwknop-log_msg.o ../lib/libfko.la ../common/libfko_util.a
libtool: link: gcc -g -O2 -Wall -Wformat -Wformat-security -fstack-protector-all -fstack-protector -D_FORTIFY_SOURCE=2 -Wall -Wformat -Wformat-security -fstack-protector-all -fstack-protector -D_FORTIFY_SOURCE=2 -o .libs/fwknop.exe fwknop-fwknop.o fwknop-config_init.o …
```
=> Fix client/Makefile.am to work with libtool 2.4.6 from Cygwin

server/access.c
If a base64 encoded key is provided twice, add_acc_b64_string() was using malloc to allocate a second key value without first freeing the previous value.  This patch adds null checks, and frees the previous memory usage if needed.
=> Check for non-null pointer value

Doxyfile, server/access.c, server/access.h, server/cmd_cycle.h, server/cmd_opts.h, server/config_init.h, server/extcmd.h, server/fwknopd.h, server/fwknopd_common.h, server/fwknopd_errors.h, server/incoming_spa.h, server/nfq_capture.c, server/nfq_capture.h
server/cmd_cycle.h lacks a bit more detail for a couple functions.  This PR finishes about half of server/*
Note that this pull request does remove the non-existent clear_configs() function.
Another issue I've discovered is that Doxygen isn't sure how to handle a situation where two functions share the same name. For example, log_msg() exists in both the server and client code.  Perhaps in a case like this we should rename one function to client_log_msg().
=> Adds more Doxygen documentation in preparation for 2.6.9

server/fw_util_firewalld.c, server/fw_util_iptables.c
Fairly straightforward; I think it bulletproofs the nat-dns feature quite a bit.  Allowing non-valid hostnames could be quite problematic, especially since those are part of strings that get executed as root.
edit: remove derp
=> Add nat validation

server/tcp_server.c, test/test-fwknop.pl, test/tests/rijndael.pl
Just a bit of hack, but it's the only solution I have for getting the spa over tcp test to pass while in code coverage mode.
=> Test suite: Adds workaround for tcp server test

client/fwknop.8.in, doc/fwknop.man.asciidoc
This is a minor patch by Franck Joncourt, which is applied during Debian packaging, but may as well be pushed upstream.
=> Fix spelling error in documentation

doc/libfko.texi, lib/fko.h, lib/fko_error.c, server/access.c, server/access.h, server/config_init.c
found those flagged on https://lintian.debian.org/full/packages@qa.debian.org.html#fwknop_2.6.0-4 when I was reading up on the debian packaging process
=> fix spelling errors flagged by Debian lintian

README.md
link to coverity from README points to the svg picture, instead of the extended stats on coverity website, which was probably the intention.
Attached markdown version of the expected link.
=> Proper link to coverity scan results

client/config_init.c
I'm not sure how "fwknop" is supposed to be pronounced, but it's "*an* fwknop" everywhere else, so let's standardize on this.
=> Fix indefinite articles

erlang/LICENSE, erlang/README.md, erlang/rebar.config, erlang/rebar.lock, erlang/src/fwknop.app.src, erlang/src/fwknop.erl, erlang/src/fwknop_tests.erl
Standalone Erlang client implementation, co-authored with @garryh. Currently supports Rijndael, GPG support is very limited in Erlang.
=> [erlang] initial checkin of Erlang client

.gitignore, erlang/rebar.config, erlang/rebar.lock
Updating project .gitignore for Erlang build artifacts, removing related rebar.lock, and explicitly setting pkcs7 dependency to master branch.
=> [erlang] updating Erlang .gitignore and build dependencies

erlang/README.md, erlang/src/fwknop.erl, erlang/src/server.erl
Adding complimentary Erlang server-side component to receive and decode SPA message. Currently a reference implementation that simply decodes the pkt, does not manipulate a firewall/iptables.
=> Adding Erlang server component

common/netinet_common.h, configure.ac
This commit allows building fwknop on NetBSD. fwknop detects support for the pf(4) packet filter there, but was missing a definition for `ETHER_IS_VALID_LEN` in the standard headers. Using the same workaround as for OpenBSD bridged this gap.
I have not tested if this works.
=> Let fwknop build on NetBSD

client/config_init.c, client/fwknop.c, client/http_resolve_host.c, common/fko_util.c, lib/fko_common.h, lib/fko_decode.c, lib/fko_message.c, lib/fko_user.c, server/access.c, server/incoming_spa.c, server/utils.c
These two commits address two types of warnings:
- an issue with the pre-processor (apparently a harmless typo)
- issues with functions from ctype(3) potentially revealing actual bugs.
=> Addressing most warnings

client/spa_comm.c
This trivial commit fixes error messages when failing to connect over TCP: the actual error is missing from the output.
=> Fix incomplete format string upon errors

client/spa_comm.c
In fwknop, the values generated using random() are only used for the ID
field of raw IP packets. As indicated in the corresponding comments,
this value does not really matter, and it does not really have to be
random at all.
However, it should not hurt to initialize the entropy pool before
generating random values. arc4random() would be a better choice, but it
is not portable across the range of systems currently supported by
fwknop.
=> Seed random() at least a bit before using random()

client/fwknop.c
strlcat() needs to be informed about the actual size of the buffer. Two
calls simply used the size expected, thus potentially allowing
stack-based buffer overflows.
There is no direct security impact in this case, since the code affected
is on the client side, and the input comes from configuration
information.
=> Fix two erroneous calls to strlcat()

client/http_resolve_host.c, configure.ac, server/extcmd.c, server/fw_util_firewalld.h, server/fw_util_iptables.h, server/fw_util_pf.h, test/test-fwknop.pl, test/tests/configure_args.pl
execvp() is (usually) equivalent to execvpe(), without enforcing any
change to the environment. However, unlike execvp(), execvpe() is not
standardized by POSIX, and may therefore not be available nor detected
when configuring the project (like on NetBSD).
No place could be found in fwknop to be using execvpe() and changing the
environment. Therefore it seems only logical (and safer) to use execvp()
instead.
This also updates the tests to reflect this change.
=> Use execvp() instead of execvpe()

client/http_resolve_host.c, client/spa_comm.c
For some reason the HTTP headers generated for GET requests in the client code are using HTTP/1.0, whereas the "Host" header is always provided anyway. It seems to me that it should do no harm to use HTTP/1.1 instead (not tested).
=> Use HTTP/1.1 when communicating over HTTP

client/config_init.c, client/fwknop.c, client/utils.c, client/utils.h, configure.ac, server/access.c, server/config_init.c, server/fwknopd.c, server/replay_cache.c, server/utils.c, server/utils.h
These changes leverage fstat() to avoid TOCTOU conditions. This also requires fileno() when using fopen(). Judging from the existing code, fileno() may not be available on every platform (like Windows). In this case the fallback code is equivalent to the previous one with the flaw.
Reported in Coverity as issue 1355235.
=> khorben/coverity/1355235 TOCTOU

extras/apparmor/usr.sbin.fwknopd
The missing binary was preventing fwknopd from starting.
=> Fix AppArmor profile for Debian unstable

configure.ac, m4/gpgme.m4
Thanks @damienstuart for help with this.  It builds and works on macOS 14.3 with up-to-date Homebrew and Xcode.
=> Fixes for macOS build

lib/fko_encryption.c
I encountered a crash while using the client with GPG. I found out the problem comes from a wrong buffer length given to snprintf. I think the problem didn't occur before either because I had an older linux kernel or because of some sysctl setting I changed to harden my configuration.
=> Fix snprintf buffer length

server/incoming_spa.c
When there are multiple stanza and they are tried one after the other, there should not be a log with level “warning”, but only a log with level “info”.
The `log_msg` in the `else` is the previous one, it is the same message as the first one of the `if` but with level DEBUG, and the second one in the `if` is new. It has the level INFO which is the same level as the log just before "(stanza # 1) SPA Packet from IP: x.x.x.x received with access source match", so that it is coherent to see what stanza is checked then its result.
This will help monitoring the logs with less WARNINGs.
Issue: #337
=> Soften the message when the stanza is not the correct one

extras/apparmor/usr.sbin.fwknopd
Appears to be requested/needed on Debian unstable.
=> Add missing /etc/gai.conf to AppArmor profile

lib/fko_encryption.c, win32/config.h
Fixes build on Win32 with VC14. Do defines similar to what cURL does. Also add better GPG support on a Windows build.
=> Fix build with Win32 VC14

extras/systemd/fwknopd.service
Per the systemd documentation (https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/#cutthecraphowdoimakesurethatmyservicestartsafterthenetworkisreallyonline), both Wants and After are required when
using the network-online.target.
Originally reported on the Debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949323
=> Add missing "Wants" directive in systemd unit file

extras/systemd/fwknopd.service
Right now, when network interfaces go down and then back up (e.g. undocking and re-docking a laptop), fwknop-server dies and can no longer be used to open the firewall.
This causes the daemon to restart when it fails for any reason other than normal shutdowns/restarts.
=> Restart fwknop-server on failure

client/getpasswd.c, lib/fko_message.c
Fix two warnings that happen with "Apple clang version 15.0.0 (clang-1500.1.0.2.5)".  With this commit the client builds on macOS with zero warnings.
=> Fix compile warnings
